apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  os: { name: linux }
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: mysql
    image: mysql:5.7
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db-volume
      # readOnly: true
  volumes:
  - name: db-volume
    hostPath:
      path: /data/db/mysql # directory location on host
      type: DirectoryOrCreate